apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  selector:
    matchLabels:
      app: react-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: java-spring-boot  
        image: tushargayakwad/react-app:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: react-deployment
spec:
  selector:
    app: react-deployment
  ports:
    - protocol: TCP 
      port: 5173
      targetPort: 5173
  type: NodePort